name = "xinhexin-api"
main = "api/worker.js"
compatibility_date = "2024-12-01"

workers_dev = true


[[kv_namespaces]]
binding = "POLICY_KV"
id = "8687c597a13548f58c7236090ad56287"

[[d1_databases]]
binding = "DB"
database_name = "xinhexin_prod"