name = "xinhexin-api"
main = "api/worker.js"
compatibility_date = "2024-12-01"

workers_dev = true

[[kv_namespaces]]
binding = "SMS_KV"
id = "487f5073f6be4ad6bc4f5380a9a16d14"

[[d1_databases]]
binding = "DB"
database_name = "xinhexin_prod"